### ISSUE TITLE
Is mixpanel.people.set_once missing from the node API?

### ISSUE THREAD

**Issue by Kemingkai** [mixpanel/mixpanel-node#103]
I'd like to use the same "mixpanel.people.set_once" function that's available in the JS library to set People profile properties only once at the time of initial registration. I didn't see it in the documentation on this git repo, and I wasn't able to fire it succesfully when I tested it.

Wondering if it is being added soon or if there's some slightly different syntax when using it on node. 

Thanks

**Comment by Kemingkai** [comment]
And to add to that train of thought: is there any plan to add the mixpanel.register functions to the Node library?

We have several events that are much more accurately tracked server side so the Node library is really helpful for us.

Thank you

**Comment by mixpanel-travisci** [comment]
If you check out the source for mixpanel.register in the JavaScript
library, you'll see that .register is a client side storage method that
uses LocalStorage or the cookie to store properties between sessions.

So, on the server, you need to include event properties directly with each
.track call instead of using .register to record state at the time the
event was triggered or .people.set to record the current state.

**Comment by Kemingkai** [comment]
Thanks for your response. 

**mixpanel.register**
I see - so there's no point in using register on the server side because Mixpanel sets the super properties by creating a local variable stored in the session cookie. I assumed the super property would be stored on the Mixpanel server and applied to future events that hit the Mixpanel servers with the same distinct_id (or matching alias).  I understand it could be a huge infrastructure change to add that feature on the Mixpanel side, but it would be awesome if you did =)

**mixpanel.people.set_once**
 I didn't end up trying mixpanel.people.set() because I didn't see it listed in your documentation. Maybe it's just missing from the list of available methods in the Node API? https://github.com/mixpanel/mixpanel-node

**Comment by tdumitrescu** [comment]
You're right, the README didn't include a `set_once` example so I added one just now (pulled from https://github.com/mixpanel/mixpanel-node/blob/master/example.js). Hope that helps!

**Comment by Kemingkai** [comment]
Cool, thanks for the final update
