### ISSUE TITLE
README related tool - mixpanel-cli

### ISSUE THREAD

**Issue by FGRibreau** [mixpanel/mixpanel-node#107]
Hello !

I just wanted to let you know that I've built [a CLI over mixpanel-node](https://github.com/FGRibreau/mixpanel-cli) (it's sad that mixpanel-node is not built itself over an [API description file](https://github.com/FGRibreau/mixpanel-cli/blob/master/protocol.json)), would you accept a PR on the README.md that would add a "related tool" section?

**Comment by tdumitrescu** [comment]
Sure, we'd be happy to include links to related or alternative clients in the README.

**Comment by FGRibreau** [comment]
@tdumitrescu done :)
