### ISSUE TITLE
Add example with IP address tracking

### ISSUE THREAD

**Issue by oturnermajor** [mixpanel/mixpanel-node#111]
It would be helpful to have an example of an IP address being passed along with a `mixpanel.track` or `mixpanel.people` call, as described in this blog post: https://blog.mixpanel.com/2015/07/06/community-tip-how-to-keep-properties-consistent-across-client-and-server-libraries/

The examples in the blog post are in PHP and I'm not sure how they translate to the Node SDK. I would guess that a track event with an IP address would look like this: 

```javascript
mixpanel.track('sign_up', {
  distinct_id: id,
  ip: '229.92.91.139'
})
```
And that an IP address added to a people tracking event would look like this; 
```javascript
mixpanel.people.set(
  $first_name: first_name,
}, '229.92.91.139')
```

Can anyone confirm if this is correct or not?

**Comment by siboulet** [comment]
This is correct for `mixpanel.track`. Not sure for `mixpanel.people.set`, I *think* it might be:

```js
mixpanel.people.set(
  $first_name: first_name,
}, { $ip: '229.92.91.139'})
```

According to https://github.com/mixpanel/mixpanel-node/issues/89#issuecomment-232882628

**Comment by freeall** [comment]
@siboulet does it work if you do `.set({}, {$ip: '...'})`?

**Comment by tdumitrescu** [comment]
There are now some examples in the README of how to set IP: https://github.com/mixpanel/mixpanel-node/commit/a3390a78a150e004048711b7791ce4781c561a5c

Please feel free to reopen if you have trouble with these.
