### ISSUE TITLE
batch should POST

### ISSUE THREAD

**Issue by cruzanmo** [mixpanel/mixpanel-node#114]
"To send a batch of messages to an endpoint, you should use a POST instead of a GET request. Instead of sending a single JSON object as the data query parameter, send a JSON list of objects, base64 encoded, as the data parameter of an application/x-www-form-urlencoded POST request body." from https://mixpanel.com/help/reference/http#batch-requests

It seems that the import_batch is using GET with query param.

**Comment by premasagar** [comment]
I find the GET request triggers a 414 "Request URI too long" error from the Mixpanel API server. Presumably changing the library to use POST instead would resolve it.

**Comment by cruzanmo** [comment]
@premasagar that is correct -- I changed it to POST in the #113 PR which is still open.
