### ISSUE TITLE
time_event function

### ISSUE THREAD

**Issue by FelikZ** [mixpanel/mixpanel-node#115]
Hi,

I am using mixpanel in Electron application on Windows.

I want to implement session duration tracking using [following help page](https://mixpanel.com/help/questions/articles/how-do-i-track-session-length)#Javascript as reference.

It suggests to use `time_event` function but it does not exist in nodejs module.

Searching around the web and this issue tracker the only thing I came with is to use `time`.

I tried to use `time`property on application close event:
```javascript
    tracker.track('Application Closed', {
        "distinct_id": machine_id,
        "release": `${os.type()} ${os.release()}`,
        "source": "desktop app",
        "time": moment.utc().toISOString()
    }, app.quit);
```

But I got this:

<img width="557" alt="screenshot 2017-03-08 08 17 15" src="https://cloud.githubusercontent.com/assets/1080269/23693993/b08a17da-03d7-11e7-922c-33e0c820d1c6.png">

Is there workaround to track session length, rather then calculating itself in application?

Thanks

**Comment by tdumitrescu** [comment]
Even if you added a timestamp correctly in your `time` field, that would give you the current time, not your session duration. Although `time_event` hasn't been implemented in the node lib, it's pretty easy to add a one-off for your application:
```js
// session begins: this is where you would call time_event() in another lib
const sessionStartTime = new Date().getTime();

// then when the user quits
tracker.track('Application Closed', {
  "distinct_id": machine_id,
  "release": `${os.type()} ${os.release()}`,
  "source": "desktop app",
  "Duration": new Date().getTime() - sessionStartTime,
}, app.quit);
```
If you have more implementation questions, I'd suggest contacting support@mixpanel.com; they'll be quite happy to go over your code with you and work through the details.
