### ISSUE TITLE
Clone properties object at track method

### ISSUE THREAD

**Issue by KnupMan** [mixpanel/mixpanel-node#119]
Hello.
Using `mixpanel.track(event, properties)` changes `properties` object, so it can't be reused. 
Exactly it means that `token: '***'` and `mp_lib: 'node'` properties adds to the passed `properties` object.
Can it use some `clone` method?
![image](https://cloud.githubusercontent.com/assets/16997074/25207835/a6acc596-2579-11e7-9e32-bc7d4643b706.png)

**Comment by freeall** [comment]
I'll make the counter-argument that speed should be most important, and cloning the object will impact speed always. If kept as is, then it will only impact those who need it to be a new object (and thus will need to clone themselves).

**Comment by vladgolubev** [comment]
@freeall ok, so if cloning is expensive, what if lib will delete attached properties after they were sent?

**Comment by freeall** [comment]
@vladgolubev Then you should clone the data before sending it to the module.

For many modules this won't really matter, but for those that might be seeing a lot of speed they should optimize for that. Would be my point at least :)

**Comment by tdumitrescu** [comment]
If someone wants to make a PR adding an *option* to avoid mutating tracking properties, that would work very well. Maybe a config flag so it's global. That way you can do what's appropriate for your own application.
