### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by alexanderwhatley** [mixpanel/mixpanel-node#120]
Webpack is throwing the following errors at me after installing and trying to import mixpanel:
```

ERROR in ./~/https-proxy-agent/https-proxy-agent.js
Module not found: Error: Cannot resolve module 'net' in /home/alexander/Documents/Programming/reactfire/node_modules/https-proxy-agent
 @ ./~/https-proxy-agent/https-proxy-agent.js 6:10-24

ERROR in ./~/https-proxy-agent/https-proxy-agent.js
Module not found: Error: Cannot resolve module 'tls' in /home/alexander/Documents/Programming/reactfire/node_modules/https-proxy-agent
 @ ./~/https-proxy-agent/https-proxy-agent.js 7:10-24
```

**Comment by tdumitrescu** [comment]
[net](https://nodejs.org/api/net.html) and [tls](https://nodejs.org/api/tls.html) are built-in Node.js modules. If you're targeting browser environments you should use the [mixpanel-browser](https://www.npmjs.com/package/mixpanel-browser) package rather than `mixpanel-node`.

**Comment by Matheusbafutto** [comment]
I had the same issue and changing mixpanel to mixpanel-browser solved the problem.

**Comment by tdumitrescu** [comment]
Glad this seems solved, going to close this issue out.
