### ISSUE TITLE
Can I send a pushToken via mixpanel.people.set() ?

### ISSUE THREAD

**Issue by gianpaj** [mixpanel/mixpanel-node#121]
Or do I have to use the Android/iOS SDK?

I'm already sending the push token to my node.js server

**Comment by tdumitrescu** [comment]
Yes, you can set tokens via the HTTP API. See e.g. the section "Importing device tokens" in https://mixpanel.com/help/reference/ios-push-notifications#sending-device-tokens. To send a `union` request from this library, use [`mixpanel.people.union()`](https://github.com/mixpanel/mixpanel-node/blob/e993df7f0bb452e3c9484a41c392bfac74c78e2e/lib/mixpanel-node.js#L793-L804).

**Comment by tdumitrescu** [comment]
Seems resolved so will close this out - feel free to reopen if you have related lib-specific issues, or contact support@mixpanel.com for general Android/iOS usage questions.

**Comment by gianpaj** [comment]
Thanks. I believe as a reference you can also send the push token like so:
```
mixpanel.people.set(distinct_id, {
    "$android_devices": [pushToken]
});
```

**Comment by tdumitrescu** [comment]
Sure. The reason to prefer `union` over `set` is to allow for multiple devices, and the reason to use `union` rather than `append` is to keep duplicates out of the device list. But if your specific application only ever needs a single device per user, then `set` should be ok.
