### ISSUE TITLE
Update node-https-proxy dependency

### ISSUE THREAD

**Issue by chilltemp** [mixpanel/mixpanel-node#125]
Please update the node-https-proxy once they release the next version.  This will eliminate a known low severity vulnerability in one of its dependencies.  You'll need a version > 2.1.0, as it still has the vulnerability.

TooTallNate/node-https-proxy-agent#37
TooTallNate/node-https-proxy-agent#39

**Comment by tdumitrescu** [comment]
Thanks for the heads up. Looks like `node-https-proxy-agent` 2.1.1 has just been released; will bump and close out this issue once published.
