### ISSUE TITLE
Security vulnerability related to dependency https-proxy-agent

### ISSUE THREAD

**Issue by mkarazin** [mixpanel/mixpanel-node#129]
The dependency https-proxy-agent v2.1.1 used by mixpanel-node 0.9.0 has a high-severity security vulnerability.

https://snyk.io/vuln/npm:https-proxy-agent:20180402

Please update this dependency to 2.2.1 when you can. Thanks!

**Comment by tdumitrescu** [comment]
Thanks for the ping @mkarazin. v0.9.1 is now published and uses `https-proxy-agent` 2.2.1.

**Comment by mkarazin** [comment]
Thanks for the quick response and version bump!
