### ISSUE TITLE
Sending IP address does not record geolocation metadata

### ISSUE THREAD

**Issue by jkprow** [mixpanel/mixpanel-node#137]
I sent an email to Mixpanel support, but I'm adding this here as well in case it's a usage issue.

I am able to send events to Mixpanel using `mixpanel.track`. I am seeing events logging in the Live view of the Mixpanel web console. My issue is that geolocation is not working as advertised.

Below is an example request. I intercepted the request to the Mixpanel API from my server via a proxy and base64 decoded the query string, so this is the very shape the API received. Most values are omitted for security.
```
{
  "event": "Sign In”,
  "properties”: {
    "distinct_id”: X,
    "ip”: ”10.138.0.27”,
    "Email”: "X”,
    "Success ”:X,
    "User ID”: X,
    "Job Title”: "X”,
    "User Created Date”: "X”,
    "Org ID”: X,
    "Org Name": ”X”,
    "Plan Code”: ”X”,
    "Plan Name": ”X”,
    "Org Created Date”: "X”,
    "token”: "X”,
    "mp_lib": ”node”
  }
}
```
Included in my properties is an IP address at the `ip` key. According to [the docs](https://github.com/mixpanel/mixpanel-node/blame/master/readme.md#L37), if this key is included, Mixpanel will use it to generate geolocation metadata. However, when the event is viewed in the Live view of the Mixpanel web console, geolocation metadata is not available. The `ip` property doesn’t show up in any of the Properties tabs either.

I have also tried sending the IP address at the key `$ip`. In this case, `$ip` shows up in the "Your Properties” tab, but still no geolocation metadata is generated.

Has the Mixpanel API shifted, or am I doing something wrong?

**Comment by jkprow** [comment]
This was an infrastructure issue. Load balancer is failing to expose the true client IP through headers, thus I was sending an IP in private address space.

**Comment by amruth-k99** [comment]
Add these in your Nginx/load balancer server:
```
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;
```

Your Nginx server is probably not forwarding the IP address from the client website.
