### ISSUE TITLE
Is it safe to check in the client-side mixpanel token for production into Git source control?

### ISSUE THREAD

**Issue by adeperio** [mixpanel/mixpanel-node#139]
I'm using Mixpanel for a client electron app. I figured since it's client-side, just wanted to clarify if this is safe to check this token into source control?

**Comment by tdumitrescu** [comment]
Yes, the client-side tracking token that you use in `mixpanel.init()` is publishable. Just not any values that you see referred to as "API Secret" or "API Key." Feel free to write in to support@mixpanel.com if you have more usage/config questions!

**Comment by adeperio** [comment]
Awesome thanks!

**Comment by goktugyil** [comment]
I've also checked this: https://github.com/mixpanel/mixpanel-node/issues/97

I haven't seen anywhere API Key and API Secret are used at. How come? 

I'm just initializing mixpanel with `mixpanelFramework.init(MIXPANEL_TOKEN)`.

I want to add environment variables for mixpanel and, I cannot reset the current token. API Key and Secret seem to be useless, even though they are reseted. What should I do? I don't want my mixpanel token to be public knowledge.

**Comment by tdumitrescu** [comment]
Hi @goktugyil sure, if you're not doing any client-side tracking you can treat your tracking token as secret. Unfortunately you'll need some help from our support team to reset the tracking token (as opposed to the secret keys, which are used for querying data and importing data older than 5 days). You can get help at https://mixpanel.com/get-support. Sorry for the inconvenience.
