### ISSUE TITLE
Example of send_batch_requests

### ISSUE THREAD

**Issue by himanshuphirke** [mixpanel/mixpanel-node#146]
Could there be an example of send_batch_requests()
Would make usage more appropriate.

**Comment by tdumitrescu** [comment]
`send_batch_requests()` is an internal helper function that isn't available in the public API. The public methods that use it are [`mixpanel.track_batch()`](https://github.com/mixpanel/mixpanel-node/blame/dda5f08b8f817a4974c9184316844003b64f58be/readme.md#L120-L137) and [`mixpanel.import_batch()`](https://github.com/mixpanel/mixpanel-node/blame/dda5f08b8f817a4974c9184316844003b64f58be/readme.md#L152-L170) (links are to examples in README).

**Comment by himanshuphirke** [comment]
@tdumitrescu - thanks, is there a way I can use batches to update people profiles? I know there is an HTTP endpoint but was looking for this package's help if possible.

**Comment by RobinJayaswal** [comment]
@tdumitrescu I am also curious about batch updating of profiles. I occasionally need to update each profile individually on certain migrations.
