### ISSUE TITLE
Client throws "Mixpanel Server Error: null" error when mixpanel.track response is null

### ISSUE THREAD

**Issue by devendrawani** [mixpanel/mixpanel-node#152]
I have recently updated my newrelic & mixpanel client modules to latest version (5.6.1 &  0.10.1 respectively). Since then following error started appearing on calling mixpanel.track, but events are getting tracked at mixpanel.

Error: Mixpanel Server Error: null
   at IncomingMessage.<anonymous> (/node_modules/mixpanel/lib/mixpanel-node.js:136:42)
   at emitNone (events.js:111:20)
   at IncomingMessage.emit (events.js:208:7)
   at IncomingMessage.wrapped (/node_modules/newrelic/lib/transaction/tracer/index.js:188:22)
   at IncomingMessage.wrappedResponseEmit (/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:212:24)
   at endReadableNT (_stream_readable.js:1064:12)
   at _combinedTickCallback (internal/process/next_tick.js:139:11)
   at process._tickDomainCallback (internal/process/next_tick.js:219:9)
   at process.wrappedProcess (/node_modules/newrelic/lib/instrumentation/core/timers.js:15:21)

Anyone here facing same issue ? All help appreciated.

**Comment by KnupMan** [comment]
The same for me. It started long time ago from an error:
```
{
	"name":"Error",
	"message":"Mixpanel Server Error: upstream connect error or disconnect/reset before headers",
	"cause":{},
	"isOperational":true,
	"stack":"Error: Mixpanel Server Error: upstream connect error or disconnect/reset before headers\n    at IncomingMessage.<anonymous> (/pipeline/source/node_modules/mixpanel/lib/mixpanel-node.js:135:42)"
} 
```
And from March 18-19 it's another error
```
{
	"name":"Error",
	"message":"Mixpanel Server Error: null",
	"cause":{},
	"isOperational":true,
	"stack":"Error: Mixpanel Server Error: null\n    at IncomingMessage.<anonymous> (/pipeline/source/node_modules/mixpanel/lib/mixpanel-node.js:135:42)"
}
```
I am using mixpanel lib in AWS Lambda (node 8.10) and I thought it can be the reason.
@devendrawani what is the environment, where you are running `mixpanel.track`?

**Comment by devendrawani** [comment]
> The same for me. It started long time ago from an error:
> 
> ```
> {
> 	"name":"Error",
> 	"message":"Mixpanel Server Error: upstream connect error or disconnect/reset before headers",
> 	"cause":{},
> 	"isOperational":true,
> 	"stack":"Error: Mixpanel Server Error: upstream connect error or disconnect/reset before headers\n    at IncomingMessage.<anonymous> (/pipeline/source/node_modules/mixpanel/lib/mixpanel-node.js:135:42)"
> } 
> ```
> And from March 18-19 it's another error
> 
> ```
> {
> 	"name":"Error",
> 	"message":"Mixpanel Server Error: null",
> 	"cause":{},
> 	"isOperational":true,
> 	"stack":"Error: Mixpanel Server Error: null\n    at IncomingMessage.<anonymous> (/pipeline/source/node_modules/mixpanel/lib/mixpanel-node.js:135:42)"
> }
> ```
> I am using mixpanel lib in AWS Lambda (node 8.10) and I thought it can be somehow the reason. What I can confirm - the events that were tracked with error are on the Mixpanel as events that had no errors. So basically it's not a critical issue, but anyway it feels wrong to have such error.
> @devendrawani what is the environment, where you are running `mixpanel.track`?

I am using Node V8.15, running on AWS EC2 Linux

**Comment by andrewheekin** [comment]
@devendrawani experiencing the same issue in the same environment

**Comment by PavelNartov** [comment]
The same issue on Node v10.15.0, running on DO.

**Comment by jackfurr** [comment]
Error is thrown by Mixpanel when calling `Mixpanel.people.set()`, `Mixpanel.people.increment()`, and `Mixpanel.track()`

Similar problem (Client throws "Mixpanel Server Error: null"), but stack is different

**Node**: 8.10
**Mixpanel**: 0.10.2

**Error**: 
Mixpanel Server Error: null
    at IncomingMessage.<anonymous> (<removed>/node_modules/mixpanel/lib/mixpanel-node.js:136:42)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by awenner** [comment]
For anyone still following this issue — we submitted a report directly to Mixpanel, who responded with the following:

>We have carried out further investigation on our end and identified an issue with how Node.js formatted requests coupled with a bug in the new API code. Assuming there was nothing wrong with the request, then the data sent was tracked in Mixpanel where typical codes of '0' or '1' were both masked to 'null'.
>Our Engineers have deployed a fix in order to resolve this bug. 

Posting here in case they neglect to update the public Github issues.

**Comment by KnupMan** [comment]
For me issue has been resolved already for one day

**Comment by tdumitrescu** [comment]
As far as we can see, this is now resolved at the API layer, so I'm going to close this out. If anyone's still getting the `null` case please do comment here again and we'll re-open.
