### ISSUE TITLE
increment/decrement functions on groups api

### ISSUE THREAD

**Issue by idanwe** [mixpanel/mixpanel-node#169]
Is it possible to use the mixpanel node api to do increment/decrement actions on a group?

something similar to the people api
`mixpanel.groups.increment(group_key, group_id, prop, by)`

**Comment by tdumitrescu** [comment]
The Groups API only supports idempotent operations, and so increment/decrement was never added to its spec. All the available operations are currently implemented in this library; see https://developer.mixpanel.com/docs/http#adding-properties-to-a-group-profile for what's available in the spec. The Mixpanel support forum [QBQ](https://community.mixpanel.com/) is a good spot if you have questions about how to perform specific analyses, might find that you don't need incr/decr at all - Mixpanel's behavioral analysis capabilities have gotten a lot stronger recently, and a lot of questions that used to require tracking implementation changes can now be answered on the fly with post-hoc analysis.
