### ISSUE TITLE
Typescript build: Cannot find name 'Element'

### ISSUE THREAD

**Issue by StErMi** [mixpanel/mixpanel-node#176]
Hi, I've installed both `mixpanel` and `@types/mixpanel` package but when I try to do my build with `tsc` I get these errors:

```
node_modules/@types/mixpanel/index.d.ts:629:27 - error TS2304: Cannot find name 'Element'.

629     type Query = string | Element | Element[];
                              ~~~~~~~

node_modules/@types/mixpanel/index.d.ts:629:37 - error TS2304: Cannot find name 'Element'.

629     type Query = string | Element | Element[];
                                        ~~~~~~~
```

**Comment by tdumitrescu** [comment]
This is the Mixpanel SDK for Node.js. The 3rd-party type definitions that you installed are for the [Mixpanel browser SDK](https://www.npmjs.com/package/mixpanel-browser). If you're trying to use mixpanel-node, the type definitions are installed with the lib: https://github.com/mixpanel/mixpanel-node/blob/master/lib/mixpanel-node.d.ts
