### ISSUE TITLE
Wrong documentation for EU data residency

### ISSUE THREAD

**Issue by all-things-liquid** [mixpanel/mixpanel-node#178]
Hello,

I've encountered an issue when trying to change the host for EU data residency.
The [documentation](https://developer.mixpanel.com/docs/nodejs#eu-data-residency) suggests the following modification: 
```javascript
mixpanel.init(
  "YOUR_TOKEN",
  {
    host: "https://api-eu.mixpanel.com",
  },
);
```

This contradicts the [code](https://github.com/mixpanel/mixpanel-node/blob/master/lib/mixpanel-node.js), where the default config is as follows: 

```javascript
const DEFAULT_CONFIG = {
    test: false,
    debug: false,
    verbose: false,
    host: 'api.mixpanel.com',
    protocol: 'https',
    path: '',
};
```

And more importantly, it is incompatible with the way `metrics.set_config` overrides the host, as it would mess up the result of the `split` call:

```javascript
metrics.set_config = function(config) {
    Object.assign(metrics.config, config);
    if (config.host) {
        // Split host into host and port
        const [host, port] =  config.host.split(':');
        metrics.config.host = host;
        if (port) {
            metrics.config.port = Number(port);
        }
    }
};
```

I don't know if this is the right place to ask this, but could someone edit the documentation so that host becomes `api-eu.mixpanel.com`?

Thank you for your help

**Comment by tdumitrescu** [comment]
Thanks for pointing out! We'll get this fixed on the documentation site.

**Comment by jordanmnunez** [comment]
This has been fixed. Thanks again for sharing with us!
