### ISSUE TITLE
What does the test=1 query param do when config.test=true?

### ISSUE THREAD

**Issue by albertstill** [mixpanel/mixpanel-node#180]
Does this cause a no-op your side?

**Comment by jordanmnunez** [comment]
If `config.test=true` then there will always be a `test=1` in the query param of the request. So in your case, if `test=1` is passed in as a query_param it is a no-op.

https://github.com/mixpanel/mixpanel-node/blob/e24a3980d0ffbc82e2478c6ac33efbb255a7b1a0/lib/mixpanel-node.js#L110-L112
