### ISSUE TITLE
Custom logger support

### ISSUE THREAD

**Issue by iatsiuk** [mixpanel/mixpanel-node#221]
Hello,

I am writing to request a new functionality for the mixpanel nodejs package. I would like to have the ability to set a custom logger to display debug information about mixpanel. Unfortunately, using console.log breaks the logging system that uses json-based logs.

If it is possible, I am willing to prepare a pull request with the necessary changes to implement this functionality. I have identified [ts-log](https://github.com/kallaspriit/ts-log) as a suitable logger to use as a Abstract Logger Class, and I am prepared to write an adapter for console.log to conform to the [ts-log](https://github.com/kallaspriit/ts-log) interface.

Are there any limitations or considerations we should be aware of when integrating a custom logger into Mixpanel?

I believe that adding this functionality would greatly enhance the debugging capabilities of Mixpanel and improve the overall experience for developers. I look forward to your response and any guidance you can provide.

**Comment by tdumitrescu** [comment]
👍 Sure, there shouldn't be any problem with support for a custom logger passed as an option to `mixpanel.init()`.

**Comment by iatsiuk** [comment]
hi, @tdumitrescu. Thanks for the quick response.

Do I need to add unit-tests that check the correctness of the log output?

**Comment by tdumitrescu** [comment]
If it's fairly straightforward, always helpful to have tests for the new config. Doesn't have to be extensive, just want to make sure of stuff like:
- using a customer logger doesn't throw exceptions that would break tracking
- `console.log()` is still getting called in the default case

**Comment by iatsiuk** [comment]
I submitted a [pull request](https://github.com/mixpanel/mixpanel-node/pull/222) that implements the functionality described in this ticket. I'm happy to fix problems if there are any.

**Comment by tdumitrescu** [comment]
Sorry about the delay, added a few comments, looks like it's almost ready as is.
