### ISSUE TITLE
Support for using in browser when pulled in via browserify?

### ISSUE THREAD

**Issue by cymen** [mixpanel/mixpanel-node#34]
Has anyone thought of allowing this to behave like the mixpanel library in terms of using it in the browser? It does work with browserify -- it just doesn't include all of the details that the main mixpanel library does that are specific to running in the browser.

**Comment by builtbylane** [comment]
@carlsverre  bumping this issue. I agree with @cymen, it is not apparent that this library is intended for server-side.

**Comment by freeall** [comment]
@cymen @builtbylane It's called mixpanel-*node*. That should hint that it's not intended for the browser.

**Comment by builtbylane** [comment]
@freeall fair point, but with the prevalence of isomorphic node modules, I still think it's worth being explicit.

**Comment by freeall** [comment]
@builtbylane In the description it says `A node.js API for mixpanel`.

**Comment by cymen** [comment]
Why not just be explicit? https://github.com/mixpanel/mixpanel-node/pull/61

**Comment by tdumitrescu** [comment]
@freeall it's not quite so clear-cut, when it's called just 'mixpanel' on NPM. Especially unfortunate since we do want to put the in-browser client lib on NPM once it has CJS support. A README update is a good idea. @cymen thanks for the pull request!

**Comment by freeall** [comment]
@tdumitrescu true, I guess it's always a bit of the issue with modules on npm that you never really know what is it. I'll be quiet now :)
