### ISSUE TITLE
Import Multiple events at once

### ISSUE THREAD

**Issue by kuryaki** [mixpanel/mixpanel-node#36]
Im using the importer to set old data into mixpanel, but im doing it one event at the time, which is quite expensive for a couple of thousands events, is there a way to import multiple events at once, their docs say they support a JSON Array but couldnt figure it out on how to call the importer to send an Array

**Comment by ekeren** [comment]
+1

**Comment by tielur** [comment]
:+1:

**Comment by freeall** [comment]
:+1:

**Comment by tdumitrescu** [comment]
`import_batch` is now available in v0.2.0.

**Comment by tielur** [comment]
yay thanks @tdumitrescu !

**Comment by tdumitrescu** [comment]
You're welcome! And to those who've been waiting on this, apologies for the delay: we're starting to work through the backlog of issues and are taking them one at a time.
