### ISSUE TITLE
Super properties feature not supported

### ISSUE THREAD

**Issue by fabriziomoscon** [mixpanel/mixpanel-node#48]
I need to set Super properties as documented here
https://mixpanel.com/docs/properties-or-segments/how-do-i-set-a-property-every-time

I noticed there is no function to do so right now. So I was planning to send a PR with the implementation, unless anybody has started already some work to do so.

Also could @carlsverre advise on using the current function design/style for the new function

**Comment by langfors** [comment]
We are awaiting the support of super properties so we can send utm_ style campaign properties to mixpanel.  We track these on the server side in the server's session object.  Please fix so we can get our campaign info into mixpanel.

**Comment by freeall** [comment]
@langfors On the server-side you will have to add these properties to all events yourself. What you could do is to have your frontend send the properties+values to the backend and then store it on the user in your database. Then always add these properties to all events you send to Mixpanel.

**Comment by tdumitrescu** [comment]
@freeall and @joeatwork are correct. If you want some kind of superproperty behavior tied into your particular server's session-storage scheme, you'll have to manage that in your app code. If you need more guidance, we're happy to help at support@mixpanel.com.
