### ISSUE TITLE
Allow $ignore_time and other modifiers when using $unset

### ISSUE THREAD

**Issue by bcallaars** [mixpanel/mixpanel-node#51]
I am sure this is something from the main API, but the `$unset` functionality has no way of adding a `$ignore_time` according to the documentation (or the code in this library). Why is this the case? It's very frustrating to see that when we update our properties to `$unset` something, all the user profiles have a 'last seen' of less than a minute ago.

Could you point me in the right direction please?

**Comment by joeatwork** [comment]
I'm afraid this is an issue with the documentation (and the node library) rather than on the server side- the REST API does allow for it. For tracking, $unset allows all of the same operations as other people updates.

**Comment by joeatwork** [comment]
I've retitled this as a unit of work we need to do on the lib. Thanks for reporting the inconsistency!

**Comment by bcallaars** [comment]
Yeah figured that was the case. Thanks for picking it up though!

**Comment by bcallaars** [comment]
I've created a pull request for a possible solution.

**Comment by tdumitrescu** [comment]
Resolved in v0.4.0 https://github.com/mixpanel/mixpanel-node/pull/84
