### ISSUE TITLE
Token validation

### ISSUE THREAD

**Issue by Freyskeyd** [mixpanel/mixpanel-node#59]
Hey,

When i submit a request with a total failing token:

`moncullllfjmdqsjkhgflkqdjshfgkjhsdfkjghlskjdhflksjghslkdfjhglskjdfhglksjhdflgkjshdflgkjhsdflkjghslkdfjhglskjdfhglksjdfhglkjsdhfglkjsdfh`

I get a success instead of an error. I think it's an API issue.

What can i do?

**Comment by tdumitrescu** [comment]
That is indeed the behavior of the tracking API. In the interest of getting your requests turned around as quickly as possible, the server basically just checks that they're formatted and signed correctly and have gone into the data ingestion pipeline. Matching the token to an existing project happens outside of the request cycle. If you want to discuss how that might impact your specific use case, email us at support@mixpanel.com and we'll be happy to help!
