### ISSUE TITLE
Official doc for this module

### ISSUE THREAD

**Issue by bitinn** [mixpanel/mixpanel-node#62]
Been using this module recently and find it differs greatly from the client-side module.

The lack of official doc on `mixpanel.com` can be misleading because developers may incorrectly assume what isn't mentioned here is documented in the client-side doc, eg. the first line is *This library provides many of the features in the official JavaScript mixpanel library*.

I am happy to help if you are looking for maintainers (as discussed in #54), we are probably going to use mixpanel for quite a bit in our projects.

**Comment by bitinn** [comment]
Questions for example:

- due to the lack of `identify` (so we can reuse the `mixpanel` instance), must users create a people before using `distinct_id`?
- should we have an alias `$distinct_id` since it's an unique property?

**Comment by freeall** [comment]
@bitinn the module is low level in the sense that it doesn't (and shouldn't) know anything about the user, and shouldn't store any properties/values to be sent for all further events. I quite like that it's like that.

I think your first question is more to do with understanding mixpanel, than the module. Maybe I'm mistaken. Is your question that you want to know if you must create a `People` with a specific `distinct_id` before it's shown in that `Explore` view?

**Comment by bitinn** [comment]
@freeall no, I did figure out `distinct_id` event can be created before adding a people profile. I mean it would be nice to have an introduction doc like the client side js, so ppl don't assume they share the same api: https://mixpanel.com/help/reference/javascript

**Comment by freeall** [comment]
Maybe you're right. You don't think the `quick start` section in the readme helps?

**Comment by bitinn** [comment]
It certainly does, though it also took me a while to realize why `identify` is not implemented.

**Comment by bitinn** [comment]
PS: I guess some doc can be made more apparent, like the special properties doc, but that's more a mixpanel doc issue. why not open source them :)

**Comment by freeall** [comment]
I actually wrote to them about that :) Asked if they could open source the docs as well, because it would be a lot easier to make PR's for them.

**Comment by tdumitrescu** [comment]
Thanks for the suggestions @bitinn. If you have specific changes you'd like to see in the readme, the best way would be to open a pull request. Regarding your specific issues about the meaning of distinct_id and people records, perhaps a link to the official docs would be an easy fix; we don't keep these in any of the libraries as they tend not to be platform-specific but are general to Mixpanel usage. And of course, if you need answers to your own Mixpanel questions unrelated to the mixpanel-node code, the best way is to write in to support@mixpanel.com. Thanks!
