### ISSUE TITLE
Add identify support.

### ISSUE THREAD

**Issue by andrewmunro** [mixpanel/mixpanel-node#64]
Currently there is support for alias but not identify. This is needed to correctly identified pre-registered users on new devices.

https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.identify

**Comment by freeall** [comment]
The serverside implementation doesn't have an idea about which user an action came from. You have to make sure that yourself.

In the browser all the requests will come from the same id, so it's possible to do it there.

**Comment by andrewmunro** [comment]
Ah I understand now. I was using this as a client side library for webpack. This also explains some of the unusual API calls.
