### ISSUE TITLE
Support Mixpanel#identify

### ISSUE THREAD

**Issue by armchairdj** [mixpanel/mixpanel-node#69]
The official client libraries for other platorms all seem to support Mixpanel#identify. I inherited a Node codebase that integrates Mixpanel so I'm not clear whether #identify is a newer method, but regardless, it doesn't seem to be supported here (though people analytics is).

Any plans to support #identify?

**Comment by armchairdj** [comment]
For context, here's Mixpanel's documentation for setting up people analtyics: 

https://mixpanel.com/report/38013/setup/people/ 

And here are the API docs for #identify:

https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.identify

It seems like you should always call Mixpanel#identify during authentication before calling Mixpanel.people#set.

**Comment by armchairdj** [comment]
Sorry, I see now this is a dupe of https://github.com/mixpanel/mixpanel-node/issues/64 and https://github.com/mixpanel/mixpanel-node/issues/13. Given that 2 users have re-opened this feature request this year after it was first opened in 2012, maybe consider adding it to the README? Mixpanel itself does a terrible job of documenting the differences between the operation of their own client-side libraries and their server-side ones.....

**Comment by tdumitrescu** [comment]
Great idea, thanks. There's now a bit of explanation around `identify` and superproperties questions in the readme: https://github.com/mixpanel/mixpanel-node/commit/a2d88bf039a7b2a6d3ab2160c8ea377bfbd44c4a
