### ISSUE TITLE
ES6 Refactor

### ISSUE THREAD

**Issue by tejasmanohar** [mixpanel/mixpanel-node#72]
Would the maintainers of this module appreciate an ES6 refactor using Babel (transpile on `prepublish` since not everyone is on Node 4.x.x though it's LTS now)? I'd love to help out by sending PRs for that if of interest. It would not have any significant negative performance implications since we'd transpile via Babel and not use ES6 directly through V8, which hasn't all been optimized yet.

**Comment by tdumitrescu** [comment]
Sure, adding ES2015 support would be fine as long as a transpiled ES5 version remains available at `lib/mixpanel-node.js` for backwards compatibility (and maintaining the same API of course, e.g., not removing callback support etc.). At some point we'll bump major versions and drop ES5 support, but it's not quite time yet. Although we're generally not in the habit of refactoring purely for the sake of refactoring, if you want to take it upon yourself and submit some PRs that sounds great!

**Comment by tejasmanohar** [comment]
sure! i do it for fun sometimes haha. not refactoring the whole thing or anything, just a few parts that could be made cleaner w/ es6 features, and yes i'll transpile w/ babel so distributed code will be es5.
