### ISSUE TITLE
Code style / Linter

### ISSUE THREAD

**Issue by tejasmanohar** [mixpanel/mixpanel-node#73]
Looks like a lot of this is using 4 spaces and under_score naming (even for helper functions, not exposed/exported). Most wrappers follow the conventions of the language, not API. Does Mixpanel have a strict style guide that they follow for JS, or would you guys be interested in PRs to make the styling a bit more conventional and cleaner (imo/subjective)?

If there's a strict style guide, I would highly recommend a linter, which I can also PR in using (probably) ESLint to fit the existing codebase.

**Comment by tdumitrescu** [comment]
We'd be happy to add a linter step, but aren't planning on changing the style (especially not while breaking backwards-compatibility in the API). Although 2-space-indent+camelCase is a common JS convention - and if Mixpanel were restarting this project today it's what we'd use - it's by no means universal or spec'ed, and 4-space+under_score matches our browser lib (https://github.com/mixpanel/mixpanel-js).

**Comment by tejasmanohar** [comment]
Fair; spaces changes wouldn't break backwards compatibility for sure :) but camelCase would indeed.

If I cleaned some stuff up in a PR, would 2 spaces and other conventions be accepted, or should I stick to 4 spaces? No API breaking changes- that I understand.

**Comment by tdumitrescu** [comment]
Well, we don't want to use inconsistent spacing, so it would have to be a global change. I honestly don't think the subjective benefits of using 2 spaces instead of 4 would make up for the hit to the repo history (e.g., more or less resetting `git blame`).

**Comment by tejasmanohar** [comment]
Fair enough
