### ISSUE TITLE
This project is unmaintained, or what?

### ISSUE THREAD

**Issue by godspeedelbow** [mixpanel/mixpanel-node#79]
I see lots of open PRs, no responses. more than 1k downloads/day via npm.

**Comment by tdumitrescu** [comment]
Thanks for writing!!! We've been making an effort to triage new issues as they come up, but haven't had the resources to go through the backlog of old issues yet. https://github.com/mixpanel/mixpanel-node/issues/54 is probably the appropriate place to complain, as it was here first and offers an actual suggestion.

**Comment by godspeedelbow** [comment]
aight, thanks :)

**Comment by tdumitrescu** [comment]
Sorry if that was a bit snarky! We do read and prioritize feature requests, but the best way to get something implemented and released quickly is with a pull request. Code is always welcome.

**Comment by godspeedelbow** [comment]
No problem. 

My PR is failing and I'd like some feedback on that: #78

**Comment by godspeedelbow** [comment]
Haha, that sounded snarky too. I think we're all eager here to get some stuff fixed in this module, so let's get crackin'

**Comment by tdumitrescu** [comment]
Cool, taking it over to https://github.com/mixpanel/mixpanel-node/pull/78
