### ISSUE TITLE
Support in-app push notifications

### ISSUE THREAD

**Issue by curtisblanchette** [mixpanel/mixpanel-node#81]
send ios/android push notifications. We frequently use Mixpanels web UI to send out push notifications to our users and were hoping mixpanel-node could support this as well.

**Comment by tdumitrescu** [comment]
Interesting idea! Mixpanel's SDKs are made for tracking and querying. I'm afraid that interfacing with your Mixpanel account to set up and activate notification campaigns is pretty far outside the scope of this lib; there's also currently no public API for manipulating campaigns. The smart folks at support@mixpanel.com can take a look at your particular needs and help automate as much as possible.
