### ISSUE TITLE
$ip versus ip

### ISSUE THREAD

**Issue by jbdemonte** [mixpanel/mixpanel-node#89]
I'm wondering why 	although most special properties are handled with $ prefix, the "ip" is not prefixed while everywhere in the mixpanel documentation it is

    mixpanel.people.set("billybob", {
        $first_name: "Billy",
        $last_name: "Bob",
        $created: (new Date('jan 1 2013')).toISOString(),
        plan: "premium",
        games_played: 1,
        points: 0
    });

If we provide $ip in the people.set, mixpanel service does not process to the reverse location.
The code only handle the "ip" preoperty with:

            if ('ip' in $set) {
                data.$ip = $set.ip;
                delete $set.ip;
            }

**Comment by AngelKyriako** [comment]
+1 from me

I had a problem with this since I was sending $ip just like the official mixpanel documentation suggested

**Comment by jaredmixpanel** [comment]
Hi @jbdemonte and @AngelKyriako this was fixed by adding an additional "modifiers" parameter: https://github.com/mixpanel/mixpanel-node/pull/84

The correct way to specify $ip is now:

mixpanel.people.set('billybob', {
    plan: 'premium',
    games_played: 1
}, {
    $ip: '123.123.123.123'
});

The old style of putting 'ip' inside the properties parameter is maintained for backwards compatibility.

**Comment by AngelKyriako** [comment]
@jaredmixpanel thanks for the info. Could u let us know from what npm version is this ok to be used ?

**Comment by jaredmixpanel** [comment]
Released in v0.4.0 - https://github.com/mixpanel/mixpanel-node/pull/84#issuecomment-182069969

**Comment by tdumitrescu** [comment]
Thanks for clearing that up @jaredmixpanel. I'm going to close this one out; if anyone has questions feel free to reopen or write in to support@mixpanel.com.
